version: '3.1'

services:
  db:
    image: mysql
    volumes:
      - dbbase:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_hospedagem
    networks:
      - hackgrupo_net

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80
    networks:
      - hackgrupo_net

  aplicacao:
    image: saviorony/hack-grupo-01:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - hackgrupo_net

networks:
  hackgrupo_net:

volumes:
  dbbase:
